const apiUrl = {
  users: "/api/users",
  services: "/api/services",
  requests: "/api/requests",
  attachments: "/api/attachments",
  schedules: "/api/schedules",
  requestReports: "/api/request-reports",
  scheduleReport: "/api/schedule-reports",
  dashboard: "/api/dashboard",
  posts: "/api/posts",
  terms: "/api/terms",
  donations: "/api/donations",
  donationMaster: "/api/donation-master",
  postCategories: "/api/post-categories",
  programCategories: "/api/program-categories",
  programs: "/api/programs",
  sliders: "/api/sliders",
  settings: "/api/settings",
  halaqohCategories: "/api/halaqoh/categories",
  halaqohMentors: "/api/halaqoh/mentors",
  halaqohClasses: "/api/halaqoh/classes",
  halaqohRegistrations: "/api/halaqoh/registrations",
  halaqohMyPrograms: "/api/halaqoh/my-programs",
  halaqohParticipants: "/api/halaqoh/participants",
  halaqohAttendance: "/api/halaqoh/attendance",
  halaqohFollowUp: "/api/halaqoh/follow-up",
  halaqohMaterialLevels: "/api/halaqoh/material-levels",
  halaqohPromotions: "/api/halaqoh/promotions",
  halaqohReportAttendance: "/api/halaqoh/reports/attendance",
  halaqohReportParticipants: "/api/halaqoh/reports/participants",
  halaqohReportRegistrations: "/api/halaqoh/reports/registrations",
  halaqohReportPromotions: "/api/halaqoh/reports/promotions",
  halaqohReportMentors: "/api/halaqoh/reports/mentors",
  halaqohReportCategories: "/api/halaqoh/reports/categories",
  halaqohMentorClasses: "/api/halaqoh/mentor/classes",
  halaqohMentorStudents: "/api/halaqoh/mentor/students",
  halaqohMentorStudentNotes: "/api/halaqoh/mentor/students/notes",
  pageAnalytics: "/api/analytics/pages",
};

export default apiUrl;
