const apiUrl = {
  users: "/api/users",
  services: "/api/services",
  requests: "/api/requests",
  attachments: "/api/attachments",
  schedules: "/api/schedules",
  requestReports: "/api/request-reports",
  scheduleReport: "/api/schedule-reports",
  dashboard: "/api/dashboard",
  posts: "/api/posts",
  terms: "/api/terms",
  donations: "/api/donations",
  donationMaster: "/api/donation-master",
  postCategories: "/api/post-categories",
  programCategories: "/api/program-categories",
  programs: "/api/programs",
  sliders: "/api/sliders",
  settings: "/api/settings",
  halaqohCategories: "/api/halaqoh/categories",
  halaqohMentors: "/api/halaqoh/mentors",
  halaqohClasses: "/api/halaqoh/classes",
  halaqohRegistrations: "/api/halaqoh/registrations",
  halaqohMyPrograms: "/api/halaqoh/my-programs",
  halaqohParticipants: "/api/halaqoh/participants",
  halaqohAttendance: "/api/halaqoh/attendance",
  halaqohFollowUp: "/api/halaqoh/follow-up",
};

export default apiUrl;
